const allowedUrls = [
  "reproducible-builds.org",
  "chatgpt.com",
  "github.com",
  "code.earthengine.google.com",
  "drive.google.com",
  "google.com",
  "*.google.com",
  "arcgis.com",
  "github.githubassets.com",
  "*.esri.com",
  "strongvpn.com",
  "*.strongvpn.com",
  "kimi.com",
  "*.oaiusercontent.com",
  "*.amap.com",
  "yuque.com",
  "alipay.com",
  "*.microsoftonline.com",
  "accounts.google.com.np",
  "browser-intake-datadoghq.com",
  "featureassets.org",
  "prodregistryv2.org",
  "alipayobjects.com",
  "*.alipayobjects.com",
  "doi.org",
  "*.office.com",
  "*.codabench.org",
  "*.elsevier.com",
  "elsevier.com",
  "mdpi.com",
  "ngcc.cn",
  "nwr.gov.cn",
  "developer.android.com",
  "tianditu.gov.cn",
 "doi.org",
  "gee-community-catalog.org",
  "wiley.com",
  "*.wiley.com",
  "osgeo.org",
  "*.osgeo.org",
  "pypi.org",
  "*.readthedocs.io",
  "mercurial-scm.org",
  "openai.com",
  "*.openai.com",
  "*.chatgpt.com",
  "cloudflare.com",
  "live.com",
  "*.live.com",
  "mail.qq.com",
  "*.mail.qq.com",
  "*.weixin.qq.com",
  "graph.qq.com",
  "*.graph.qq.com",
  "*.wpscdn.com",
  "redux-toolkit.js.org",
  "react-redux.js.org",
  "imgcache.qq.com",
  "webextension.org",
  "*.ptlogin2.qq.com",
  "*.captcha.qq.com",
  "res.wx.qq.com",
  "aegis.qq.com",
  "*.cdn-go.cn",
   "*.aegis.qq.com",
  "captcha.gtimg.com",
  "flickerfree.org",
  "passmark.com",
  "python.org",
  "*.microsoft.com",
  "rustup.rs",
  "*.githubusercontent.com",
  "*.qqmail.com",
  "*.oaistatic.com",
  "fonts.gstatic.com",
  "*.gstatic.com",
  "*.googleapis.com",
  "*.cloudflare.com",
  "plausible.io",
  "*.visualwebsiteoptimizer.com",
  "*.cookielaw.org",
  "*.gradle.org",
  "*.hubspot.com",
  "*.nasa.gov",
  "git-scm.com",
  "*.rust-lang.org",
  "changfengbox.top",
  "wechat-article-exporter.deno.dev",
  "*.oracle.com",
  "*.cloudfront.net",
  "localhost", // 添加 localhost
  "ws", // 添加 WebSocket 协议作为通配符
  "wps.com",
  "meeting.qq.com",
  "*.aliyun.com",
  "*.alicdn.com",
  "*.github.io",
  "apktool.org",
  "*.usgs.gov",
  "researchgate.net",
  "sciencedirect.com",
  "msftconnecttest.com",
  "*.msftconnecttest.com",
  "tensorflow.org",
  "pytorch.org",
  "redux.js.org",
  "wandoujia.com",
    "10.10.0.166",
    "*.alipay.com",
    "lgincdnvzeuno.azureedge.net",
    "accounts.google.de",
    "zenodo.org",
    "ojs.aaai.org",
    "*.office.net",
    "*.readthedocs.io",
    "*.readthedocs.org",
    "*.github.com",
  "*.aliyuncs.com",
      "*.wandoujia.com",
      "zz.bdstatic.com",
      ",*.cnzz.com",
      "*.alibabachengdun.com",
      "*.sinaimg.cn",
    " fourier.taobao.com",
    "*.9game.cn",
    "*.mmstat.com",
    "*.ucdl.pp.uc.cn",
    "*.25pp.com",
    "hm.baidu.com",
    "detectportal.firefox.com",
    "*.lzu.edu.cn",
    "*.s3.amazonaws.com",
    "s.gravatar.com",
    "jsj.top",
    "mljar.com",
    "*.jinshujufiles.com",
    "nodejs.org",
    "music.163.com",
    "*.jinshujucdn.com",
    "*.newrelic.com",
    "*.music.126.net",
    "sp0.baidu.com",
    "*.126.net",
    "*.163.com",
    "*.aliapp.org",
    "*.aligames.com",
    "qzapp.qlogo.cn",
    "docs-neteasecloudmusicapi.vercel.app" ,
    "googletagmanager.com",
    "*.googletagmanager.com",
    "unpkg.com",
    "*.googlesyndication.com",
    "gitlab.com",
    "*.npmjs.com",
    "lib.baomitu.com",
    "fonts.loli.net",
   "www.npmjs.com",
   "electronjs.org",
   "gdal.org",
   "numfocus.org",
   "studiostaticassetsprod.azureedge.net",
   "vite.dev",
   "report.qqweb.qq.com",
   "ssl.ptlogin2.graph.qq.com",
   "ant.design",
   "tauri.app",
   "docs.geetest.com",
   "www.52pojie.cn",
   "*.52pojie.cn",
   "frida.re",
    "www.wjx.cn",
     "ffmpeg.org",
     "scrapy.org",
     "pptr.dev",
     "*.qt.io",
     "*.simpleanalyticscdn.com",
     "*.hsforms.net",
     "*.nvidia.com",
     "f-droid.org",
     "*.gyan.dev",
     "*.audacityteam.org", 
    "pydub.com",
    "builds.libav.org",
    "reactnative.cn",
    "cmake.org",
    "*.gongkaoshequ.com",
    "*.apta.gov.cn",
    "*.kaggle.com",
    "*.typekit.net",
    "*.kaggle.io",
    "*.kaggleusercontent.com",
    "*.yeepay.com",
    "awesome-poetry.top",
    "*.qutebrowser.org",
    "shizuku.rikka.app",
    "*.kde.org",
    "playwright.dev",
    "*.googlesource.com",
    "*.deno.dev",
    "*.sonaliyadav.workers.dev",
    "deno.com",
    "*.deno.com",
    "nuxt.com",
  "dataorigami.net",
  "*.pymc.io",
    "*.jquery.com",
    "pyro.ai",
    "pgmpy.org",
   "mc-stan.org",
   "bookdown.org",
   "bayesiancomputationbook.com",
    "scitools.org.uk",
    "projectpythia.org",
    "xarray.dev",
    "*.xarray.dev",
    "geopandas.org",
    "*.scienceconnect.io",
    "geoviews.org",
     "matplotlib.org",
     "bit.ly",
     "worldclim.org",
  "lavaan.org",
  "*.tensorflow.org",
  "*.jsdelivr.net",
  "*.theoj.org",
  "tensorflow-dot-devsite-v2-prod-3p.appspot.com",
  "keras.io",
  "img-prod-cms-rt-microsoft-com.akamaized.net",
  "analises-ecologicas.com",
  "*.azure.com",
   "jstatsoft.org",
  "marginaleffects.com",
  "acm.org",
  "jmlr.org",
  "arxiv.org",
  "*.sciencedirect.com",
  "*.sciencedirectassets.com",
  "*.ieee.org",
 "*.arxiv.org",
 "*.neea.edu.cn",
 "*.itch.io",
  "mermaid.js.org",
  "xyflow.com",
  "editor.md.ipandao.com",
  "projectstorm.cloud",
  "alyssax.com",
  "flowchart.js.org",
  "annualreviews.org",
  "cabidigitallibrary.org",
  "springer.com",
  "science.org",
  "*.google.de",
  "apsnet.org",
  "biomedicaljour.com",
  "*.live.com",
  "aka.ms",
  "*.torontomu.ca",
  "tandfonline.com",
  "*.springer.com",
  "*.adobedtm.com",
  "*.mdpi-res.com",
  "*.cloudflareinsights.com",
  "ambridge.org",
  "bam.nr-data.net",
  "*.els-cdn.com",
  "*.unl.edu",
  "publish.csiro.au",
  "*.springernature.com",
  "academic.oup.com",
  "*.riskified.com",
  "service.seamlessaccess.org",
  "g.3gl.net",
  "royalsocietypublishing.org",
  "seamlessaccess.org",
  "journals.plos.org",
  "nature.com",
  "frontiersin.org",
  "*.r-project.org",
  "plsmod.tidymodels.org",
  "*.r-lib.org",
  ]; 
const blockedUrls = [
  "*://www.google.com/search*",
  ".*firefox.*",
  ".*firefox",
  "*://camo.githubusercontent.com/*" // 用于阻止包含“firefox”的 URL 的正则表达式
];

const onBeforeRequest = (details) => {
  const url = new URL(details.url);
  const host = url.hostname;

  // 检查是否在被阻止的 URL 列表中
  const isBlocked = blockedUrls.some(pattern => {
    const regex = new RegExp(pattern.replace(/\*/g, '.*'));
    return regex.test(details.url); // 检查整个 URL
  });

  if (isBlocked) {
    console.log(`Blocked URL: ${details.url}`);
    return { cancel: true }; // 拦截请求
  }

  // 检查是否在允许的 URL 列表中
  const isAllowed = allowedUrls.some(pattern => {
    // 处理通配符
    if (pattern.startsWith("*.") && host.endsWith(pattern.slice(2))) {
      return true;
    }
    return host === pattern || host === 'www.' + pattern; // 检查主机名
  });

  if (!isAllowed) {
    console.log(`Blocked URL: ${details.url}`);
    return { cancel: true }; // 拦截请求
  }

  return { cancel: false }; // 允许请求
};

// 监听所有请求
browser.webRequest.onBeforeRequest.addListener(
  onBeforeRequest,
  { urls: ["<all_urls>"] },
  ["blocking"]
);
